import useTranslation from 'next-translate/useTranslation'
import Head from 'next/head'
import Image from 'next/image'
import Culture from '../components/Sections/Culture'
import Games from '../components/Sections/Games'
import Heading from '../components/Sections/Heading'
import Premises from '../components/Sections/Premises'
import TeamGrid from '../components/Team/TeamGrid'

const Home = () => {
  const { t } = useTranslation('common')

  return (
    <div>
      <Head>
        <title>Conwiro</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Heading />

      <Culture />

      <Premises />

      <Games />

      <TeamGrid />
    </div>
  )
}

export default Home
